- src/Services/Entities/AllTimesData/index.ts
- src/Services/Entities/BeatmapPpData/index.ts
- src/Services/Entities/GamePlayData/index.ts
- src/Services/Entities/MenuData/index.ts
- src/Services/Entities/ResultsScreenData/index.ts
Currently, you are parsing unused beatmap sections, including storyboards. 
Sometimes, storyboards can be embedded directly into .osu files, causing you to spend extra time parsing beatmap.
> fix: optimize beatmap parsing

- README.md
- packages/server/package.json
- packages/server/router/index.ts
- packages/server/router/v1.ts
- packages/server/router/v2.ts
- packages/server/utils/http.ts
- packages/server/utils/socket.ts
- pnpm-lock.yaml
`/api/calculate/pp` - Calculate pp for beatmap with custom data
- [Response example](https://github.com/KotRikD/tosu/wiki/api-calculate-pp-response-example)
- All parameters are optional
- `path` - Path to .osu file. Example: C:/osu/Songs/beatmap/file.osu
- `mode` - Osu = 0, Taiko = 1, Catch = 2, Mania = 3
- `mods` - Mods id. Example: 64 - DT
- `acc` - Accuracy % from 0 to 100
- `nGeki` - Amount of Geki (300g / MAX)
- `nKatu` - Amount of Katu (100k / 200)
- `n300` - Amount of 300
- `n100` - Amount of 100
- `n50` - Amount of 50
- `nMisses` - Amount of Misses
- `combo` - combo
- `passedObjects` - Sum of nGeki, nKatu, n300, n100, n50, nMisses
- `clockRate` - Map rate number. Example: 1.5 = DT
> New route `/api/calculate/pp`

- package.json
- packages/common/utils/config.ts
- packages/common/utils/downloader.ts
- packages/common/utils/logger.ts
- packages/game-overlay/package.json
- packages/game-overlay/src/index.ts
- packages/server/router/index.ts
- packages/server/utils/counters.ts
- packages/tosu/src/api/types/v2.ts
- packages/tosu/src/api/utils/buildResult.ts
- packages/tosu/src/api/utils/buildResultV2.ts
- packages/tosu/src/entities/AbstractEntity/index.ts
- packages/tosu/src/entities/AllTimesData/index.ts
- packages/tosu/src/entities/BassDensityData/index.ts
- packages/tosu/src/entities/BeatmapPpData/index.ts
- packages/tosu/src/entities/GamePlayData/index.ts
- packages/tosu/src/entities/MenuData/index.ts
- packages/tosu/src/entities/ResultsScreenData/index.ts
- packages/tosu/src/entities/Settings/index.ts
- packages/tosu/src/entities/TourneyManagerData/index.ts
- packages/tosu/src/entities/TourneyUserProfileData/index.ts
- packages/tosu/src/entities/UserProfile/index.ts
- packages/tosu/src/index.ts
- packages/tosu/src/objects/instanceManager/instanceManager.ts
- packages/tosu/src/objects/instanceManager/osuInstance.ts
- packages/updater/index.ts
- pnpm-lock.yaml
- editor pp
- mostly removed async and while loops
- fixed api v2 fields
- added enums to api v2
- improve errors cover
- fix console.log
- added work around for ingame overlay (better experience)
> Remove some `Async` & `While loops` + editor pp

- packages/common/utils/config.ts
- packages/tosu/src/entities/TourneyManagerData/index.ts
Adds a config option for disabling the default suppressing of messages starting with `!mp` from the tourney manager chat, allowing them to be displayed in chat and/or used for other things such as dynamic !mp timer overlays.
> Add option for displaying !mp commands in tourney manager chat

- packages/server/utils/directories.ts
I'm using tosu in a personal project of mine, and when I tried to access map data for certain songs, it was giving me a 404 error. Funny. As it turns out, such directory names contained URL reserved characters such as "#", and since the server was just running `decodeURI()` on the whole URL, it wasn't treating such reserved characters LITERALLY.
Take this directory name for example: `1032511 Hino Isuka - #be_fortunate`
Obviously, the `#` is part of the song name, thus we want to treat it as a literal part of the resource name, instead of as a page locator tag. So I implemented `encodeURIComponent()` on each part of the URL, so that it would treat the # literally, encoding it as %23. :3
> Fix bug with retrieving beatmap data due to improper URL encoding

- packages/tosu/src/api/utils/buildResult.ts
- packages/tosu/src/entities/MenuData/index.ts
follow-up to #109
tosu has regressed compared to gosu wherein it still occasionally returns the wrong map ID when certain actions occur on the tournament client (e.g. pressing panic button when gameplay starts and client #0 hasn't loaded in).
A number of tournament overlays update pick/bans using current map ID, and this flip-flopping of map IDs can mess up autopick. Of course, it's fairly trivial to fix this on the overlay side, but a regression is a regression.
> fix bad map id momentarily being sent when hitting panic button in tclient 

- packages/tosu/src/objects/instanceManager/instanceManager.ts
tosu gets stuck if the osu lazer tournament client is running alongside stable tournament client. 
this PR adds a check to ignore an osu!.exe process if it contains the `--tournament` flag used to launch lazer in tclient mode
> ignore lazer tournament client

- packages/server/assets/homepage.html
- packages/server/router/index.ts
- packages/tosu/src/entities/AbstractEntity/index.ts
- packages/tosu/src/entities/AllTimesData/index.ts
- packages/tosu/src/entities/BeatmapPpData/index.ts
- packages/tosu/src/entities/GamePlayData/index.ts
- packages/tosu/src/entities/MenuData/index.ts
- packages/tosu/src/entities/ResultsScreenData/index.ts
- packages/tosu/src/objects/instanceManager/osuInstance.ts
- packages/tosu/src/utils/converters.ts
- credits
- Switching to old method of pushing HitErrors
- Remove delay for non-tournament clients
- Prevent updating if one of values `not-ready`
- adjust spam factor for HitErrors
- Use `UTC+0` for `createdAt` on result screen
- fix `hitError` issue, and `null pointer`
> Update delay & HitErrors & improves

- packages/tosu/src/entities/GamePlayData/index.ts
- packages/tosu/src/objects/instanceManager/osuInstance.ts
Beginnig of this  video was broken https://www.youtube.com/watch?v=0Hwy6rV1lDg, and i suspect thats because of incorrect resetted previousPassedObjects
> chore: reset passedObjects before hitting first note

- packages/common/utils/agruments.ts
- packages/tosu/src/entities/GamePlayData/index.ts
- packages/tosu/src/entities/TourneyUserProfileData/index.ts
- packages/tosu/src/objects/instanceManager/osuInstance.ts
- packages/tsprocess/lib/functions.cc
this pr fixes issues when some addresses were negative when converted from int64 to unsigned version
so this just reads all addresses coming from node as uint32 instead, this shouldn't be an issue unless we plan to add lazer support
> fix: read addresses as uint32 instead of int64

- packages/tsprocess/src/process.ts
When using a wine layer for osu! on Linux, cwd doesn't fetch the osu! game folder correctly. Instead now gets the executable directory from the cmdline and formats it to be in Linux directory. Fixes #177
> Fixes setting game folder on certain linux osu-winello configurations

- packages/server/assets/homepage.js
короче, если в дефолтных коммандах FOO не указано, то оно скипало  его и не брало измененное значение в полях
> fix: Fix `settings modal` ignoring undefined fields

- packages/tosu/src/states/beatmap.ts
Related https://discord.com/channels/1056534107330445362/1334211010390655016
> Fix: tosu throwing `ENOENT` errors on paths with trailing spaces inside.

- packages/tosu/src/instances/index.ts
- packages/tosu/src/instances/lazerInstance.ts
- packages/tosu/src/instances/osuInstance.ts
- packages/tosu/src/states/beatmap.ts
- packages/tosu/src/states/global.ts
- packages/tosu/src/states/menu.ts
- packages/tosu/src/utils/converters.ts
The function `cleanPath` sanitizes the paths passed, removing special chars (that would never be in a path, unless incorrect readout), trimming trailling spaces (similar to #290 ) and using utf-8 as encoding (hopefully fixing [this issue](https://discord.com/channels/1056534107330445362/1334946353096425566))
> Fix: Ensure `utf-8` encoding & path cleanup.

- packages/tosu/src/utils/converters.ts
Because I'm stupid.
added comments, explicit utf-8 conversion and fixed a ducking typo in the return line (`paths` => `path`)
> refactor(tosu/utils): `cleanPath` function.

- packages/common/utils/downloader.ts
Tries to fix `EPROTO ssl3 error "wrong version number"`
Has not been tested as I do not encounter the issue but I believe the issue only appears for people who use the bundled nodejs package.
> fix: Loosen `node20`'s OpenSSL default TLS handshake restrictions.

- packages/tosu/src/index.ts
Became a common issue...
The only issue here is that OneDrive users can change the path to whatever they desire, so... this only checks default OneDrive directories. But I guess it's a good addition no matter what.
> feat: Disallow tosu startup under OneDrive default directories.

- packages/tosu/src/memory/lazer.ts
Noticed this a while ago, but didn't give it a serious thought until I added the lazer's built-in pp component on the screen and saw the big difference. The deviation is linear, the longer the map, the bigger the offset.
Talked to Cherry about it, apparently it was just a misassignment.
https://github.com/user-attachments/assets/3c60790e-7b4a-4bd3-b76f-3e27c0c77f88
https://github.com/user-attachments/assets/2cbe885f-f9ea-47a6-9cba-fb73088a9ca4
> fix realtime pp calc for the standard ruleset in lazer

- packages/tosu/src/states/beatmap.ts
Skips calculating mania beatmap pp while outside of gameplay which temporary solves the data freezing issues. (Only happening on lazer afaik)
> the cause is mania hitresult generation when only acc is given, its basically bruteforcing them until it finds the best possible one which is pretty slow
> Fix: Temporary skip mania pp calculation outside gameplay state

- packages/tosu/src/api/types/v1.ts
- packages/tosu/src/api/types/v2.ts
- packages/tosu/src/api/utils/buildResult.ts
- packages/tosu/src/api/utils/buildResultV2.ts
- packages/tosu/src/states/beatmap.ts
- packages/tosu/src/states/gameplay.ts
This PR implements a new pp value called `maxAchievable` that indicates the maximum pp value a user could be getting from their play if they fc the rest of the map. This is similar to gosu's old `maxThisPlay` property, so it's a step towards gosu-tosu compatibility. (more or less...)
**Q: How is this any different from `play.pp.fc`?**
**A:** The `play.pp.fc` does not take account of misses; it shows the PP value that could have been achieved only if the player would have **never missed.** The `maxAchievable` value takes account of **all** hit judgements (300s,100s,50s & misses).
---
**!!** There's a few things to consider before merging, such as compatibility issues.
Since this PR also renames `maxAchievedThisPlay` to `maxAchieved`, there are two ways of approaching future issues:
1. …
> feat: Implement `maxAchievable`.

- packages/ingame-overlay/main/index.ts
Fix ingame overlay alignment when scale factor is not 100%.
> fix: disable chromium scaling

- packages/ingame-overlay-updater/src/index.ts
- packages/ingame-overlay/main/index.ts
- packages/ingame-overlay/main/overlay/manager.ts
- packages/ingame-overlay/package.json
- packages/tosu/src/instances/manager.ts
- pnpm-lock.yaml
* Redirect ingame overlay stdout, stderr to debug, debugError (they are verbose)
* Properly track the status of overlay process. This fix the issue tosu needs to restart completely to start ingame overlay again once the overlay is closed by user.
* close #360 pr(I included the commit before the refactor)
* add debug log when ingame overlay fail to launch due to an another instance already running(by another tosu or manual launch).
* a bit of asyncification (async `setTimeout`)
* fix ingame overlay failing due to lack of ipc access permission when osu! is launched with lower permission user than tosu
* apply start option to prefer discrete gpu
> feat: redirect in-game overlay logging, process status tracking

- packages/common/utils/config.ts
- packages/common/utils/logger.ts
- packages/tosu/src/index.ts
As discussed: if the folder exceeds 500MB, it's going to delete all files except the one currently in use.
The log message could be better tho, but whatever.
> feat: Clear `logs` directory if it's size becomes significant.

- packages/ingame-overlay/package.json
- packages/ingame-overlay/src/index.ts
- packages/ingame-overlay/src/input.ts
- packages/ingame-overlay/src/process.ts
- pnpm-lock.yaml
* remove window default menu
* apply `in-process-gpu` switch for less overhead
* update `asdf-overlay-node` to v0.7.3
> feat: bump overlay lib, overlay process tweaks

- packages/ingame-overlay/package.json
- pnpm-lock.yaml
Embed vcrt in overlay dll so it doesn't fail silently without `vcruntime140.dll` installed.
* bump `asdf-overlay` to v0.8.2
> feat: embed vcrt in overlay dll

- packages/tosu/src/instances/index.ts
- packages/tosu/src/instances/osuInstance.ts
- packages/tosu/src/states/beatmap.ts
- packages/tosu/src/states/global.ts
- packages/tosu/src/states/menu.ts
- packages/tosu/src/utils/converters.ts
- function now actually does something (blame it on me, I'm the culprit)
- changed it's name to actually represent what it does.
- it's now using the system's path separator and depends on nodejs to normalize it to utf-8
things I have to do bef merge:
> fix: ensure paths are sanitized correctly.

- packages/tosu/src/memory/lazer.ts
Stumbled upon it while trying to fix/update my overlay. I thought that the "Classic" mod in mania had settings in the past, but I guess [that's not the case](https://github.com/ppy/osu/commits/master/osu.Game.Rulesets.Mania/Mods/ManiaModClassic.cs)
> fix: Fix trying to read nonexistent "Classic" mod's settings in osu!mania
