tosuapp/tosu

src/Api/Utils/BuildResult.ts
src/Api/Utils/types.ts
src/Services/Entities/BeatmapPpData/index.ts
src/Services/Entities/MenuData/index.ts

``rosu-pp`` provide multiple strains for some modes, but tool provide only one

add support for multiple strains

---

packages/tsprocess/lib/process.h

Fixes the problem where region scanner will skip RW region

fix: use protect check instead of state for region scanner

---

packages/tosu/src/api/router/gosu/v1.ts

fix: fix import

---

packages/server/router/index.ts
packages/server/router/v1.ts
packages/server/router/v2.ts
packages/server/utils/http.ts
packages/tosu/src/api/types/v2.ts
packages/tosu/src/api/utils/buildResultV2.ts

AR, OD, CS, HP to lowercase
and `play.name` to `play.playerName`

Rename fields for api v2

---

packages/tosu/src/entities/GamePlayData/index.ts

fix: replayUIVIsible not working properly

---

.github/workflows/deploy.yml

This PR changes the `deploy & build` workflow behaviour by restricting action path to client-related files. (+ some reformatting)

feat: Improve GitHub Workflow (deploy.yml)

---

packages/common/package.json
packages/common/utils/config.ts
packages/common/utils/logger.ts
packages/game-overlay/src/index.ts
packages/server/router/index.ts
packages/server/utils/socket.ts
packages/tosu/src/entities/AllTimesData/index.ts
packages/tosu/src/entities/BassDensityData/index.ts
packages/tosu/src/entities/BeatmapPpData/index.ts
packages/tosu/src/entities/GamePlayData/index.ts
packages/tosu/src/entities/MenuData/index.ts
packages/tosu/src/entities/ResultsScreenData/index.ts
packages/tosu/src/entities/TourneyManagerData/index.ts
packages/tosu/src/entities/TourneyUserProfileData/index.ts
packages/tosu/src/index.ts
packages/tosu/src/objects/instanceManager/osuInstance.ts
packages/tosu/src/objects/memoryBase.ts
packages/tosu/src/objects/memoryPatterns.ts
packages/updater/index.ts
pnpm-lock.yaml

we only use colored console.log
pros:
- no winston

Remove `winston`

---

packages/common/index.ts
packages/common/utils/config.ts
packages/common/utils/gosu.ts
packages/game-overlay/src/index.ts
packages/tosu/src/objects/instanceManager/osuInstance.ts

https://github.com/KotRikD/tosu/issues/132

Create `config.ini` on startup

---

packages/common/utils/agruments.ts
packages/tosu/src/api/types/v2.ts
packages/tosu/src/api/utils/buildResultV2.ts
packages/tosu/src/api/utils/buildResultV2Precise.ts
packages/tosu/src/entities/BeatmapPpData/index.ts
packages/tosu/src/objects/instanceManager/instanceManager.ts

KeyOverlay & HitErrors for tourney clients

---

packages/common/utils/config.ts
packages/server/assets/homepage.html
packages/server/assets/homepage.js
packages/server/index.ts
packages/server/router/socket.ts
packages/server/utils/counters.ts
packages/server/utils/htmls.ts
packages/server/utils/http.ts
packages/server/utils/index.ts

`Socket` and `Api` access permissions

---

packages/server/package.json
packages/server/router/index.ts
packages/tosu/package.json
packages/tosu/src/entities/BeatmapPpData/index.ts
packages/tosu/src/entities/GamePlayData/index.ts
packages/tosu/src/entities/ResultsScreenData/index.ts
pnpm-lock.yaml

Based on https://github.com/MaxOhn/rosu-pp/pull/43 for latest pp rework (I believe?)

feat: pp rework

---

packages/tosu/src/memory/stable.ts
packages/tosu/src/states/settings.ts

Change configurationAddr and check for skinAddr is zero

---

packages/tosu/src/api/types/v2.ts
packages/tosu/src/api/utils/buildResult.ts
packages/tosu/src/api/utils/buildResultV2.ts
packages/tosu/src/states/beatmap.ts
packages/tosu/src/states/gameplay.ts

Revert "feat: Implement `maxAchievable`."

---

packages/ingame-overlay/electron.vite.config.mjs
packages/ingame-overlay/main/overlay/process/index.ts
packages/ingame-overlay/main/overlay/process/input.ts
packages/ingame-overlay/package.json
packages/ingame-overlay/preload/index.ts
pnpm-lock.yaml

1. Hard coded keybind from the previous overlay(shift + ctrl + space)
2. Electron offscreen input is somewhat limited. I did best effort.
3. IME doesn't work correctly yet if osu! is not using IME(not focused on text input). However this is not a big problem for configuration. English input works without IME.
4. Cursor works
Showcase: https://www.youtube.com/watch?v=1yhLjEBmb4Q

feat: ingame overlay editor

---

packages/ingame-overlay/main/index.ts

* Related to #353
* Need to test if this flag is actually effective

chore: prefer discrete gpu on laptop environment

---

packages/tosu/src/states/gameplay.ts

This PR fixes some issues regarding performance points calculation, specifically:
tested on both lazer and stable. (I've learned my lesson..)

fix: pp calc improvements

---

packages/tosu/src/states/beatmap.ts
packages/tosu/src/states/gameplay.ts
packages/tosu/src/states/resultScreen.ts

at this point, my PRs should be tagged the `bug` label.
or.. we should add test scenes :D (haha..)

Fix mania freezes & Fix pp related issues

---

packages/common/enums/osu.ts
packages/tosu/src/api/types/v2.ts
packages/tosu/src/api/utils/buildResultV2.ts
packages/tosu/src/memory/lazer.ts
packages/tosu/src/memory/stable.ts
packages/tosu/src/states/settings.ts
packages/tosu/src/utils/settings.types.ts

scroll speed per beatmap not available for stable

feat: Add mania scroll speed & scroll direction (scroll direction lazer only)

---

packages/server/assets/report.html
packages/server/package.json
packages/server/router/index.ts
packages/server/utils/report.ts
pnpm-lock.yaml

feat: New API endpoint to generate debug configuration report

---

packages/tosu/src/instances/lazerInstance.ts

fix: Make sure cache folder exists before writing

---

packages/common/utils/manipulation.ts
packages/tosu/src/api/types/v1.ts
packages/tosu/src/api/utils/buildResult.ts
packages/tosu/src/api/utils/buildResultSC.ts
packages/tosu/src/api/utils/buildResultV2.ts
packages/tosu/src/memory/index.ts
packages/tosu/src/memory/lazer.ts
packages/tosu/src/memory/stable.ts
packages/tosu/src/memory/types.ts
packages/tosu/src/states/gameplay.ts
packages/tosu/src/states/resultScreen.ts
packages/tosu/src/states/types.ts
packages/tosu/src/utils/calculators.ts

didnt tested on mania with score v2 enabled

fix: Fix lazer grades

---

packages/ingame-overlay-updater/src/index.ts
packages/ingame-overlay-updater/tsconfig.json
packages/tosu/src/instances/manager.ts

do not trust github file change, i only added try catch in `updater/index.ts`
https://github.com/user-attachments/assets/9e37473b-6516-498c-acb2-e57a17543de7

FIx EPERM issue

---

packages/tosu/src/memory/lazer.ts

for taiko, mania (ctb doesnt have it)

fix: Fix empty hitErrors and 0 UR

---

README.md

preview: https://github.com/tosuapp/tosu/tree/chore/readme

chore: added few badges to readme + fix twitter logo

---

packages/server/router/index.ts

https://discord.com/channels/1056534107330445362/1422665392551366656

fix: Fix overlays which displays directory files

---

packages/common/index.ts
packages/common/tsconfig.json
packages/common/utils/config.ts
packages/common/utils/config.types.ts
packages/common/utils/context.ts
packages/common/utils/logger.ts
packages/ingame-overlay-updater/tsconfig.json
packages/ingame-overlay/tsconfig.json
packages/server/assets/homepage.js
packages/server/assets/homepage.scss
packages/server/index.ts
packages/server/router/index.ts
packages/server/tsconfig.json
packages/server/utils/counters.ts
packages/server/utils/htmls.ts
packages/server/utils/report.ts
packages/server/utils/socket.ts
packages/tosu/src/index.ts
packages/tosu/src/instances/manager.ts
packages/tosu/src/states/beatmap.ts
packages/tosu/tsconfig.json
packages/tsprocess/tsconfig.json
packages/updater/index.ts
packages/updater/tsconfig.json

This PR contains a full rewrite of the internal config handling, replacing the scattered procedural functions with a centralized `ConfigManager` class to encapsulate all configuration logic.
My main goal on this rewrite was to get rid of the countless chains of `if...else`es and weird, unreadable conditions.
I also wanted to rewrite the logic of env syncing, as there was no flow logic followed.
Before, in order to implement a new property, you had to mention it in a couple of places in order for tosu to actually aknowledge and correctly update it.
This PR introduces a single `envSchema` as the source of truth for all config elements; basically an array with the following interface:
```ts
interface { key: string; binding: string; default: unknown; }
```
I rewrote this with type safety in …

feat: config rewrite
